#!/bin/bash

# Array of arguments
#arguments=("1300" "1400" "1500" "1600" "1700" "1800" "1900" "2000")
arguments=("100" "200" "300" "400" "500" "600" "700" "800" "900" "1000")

# Loop through the array and run the script with each argument
for arg in {25..500}; do
    echo ""
    echo ""
    echo ""
    echo ""
    echo ""
    echo ""
    echo "== Running with size $arg"
    ./test_pass "$arg" 2> ./dataSquare64/$arg.txt
done
