#!/bin/bash
mkdir build
cd build && cmake .. && make
cd ../tests
python3 make_tests.py ${1}
rm *.ll test-lru
clang -emit-llvm -S test-${1}.c -Xclang -disable-O0-optnone -o test-lru.ll
opt -load-pass-plugin=../build/tilingpass_lru/tilingpass_lru.so -passes="tilingpass_lru" test-lru.ll -o test-lru-output.ll
# opt -load-pass-plugin=../build/tilingpass/tilingpass.so -passes="tilingpass,dot-cfg" test-lru.ll -o test-lru-output.ll
clang test-lru-output.ll -Xclang -disable-O0-optnone -o test-lru
clang -O0 test-${1}.c -o test-unblocked
# cat .main.dot | dot -Tpdf > test-lru-${1}.pdf
echo "== Running non-tiled test ..."
valgrind --tool=cachegrind --D1=32768,512,64 ./test-unblocked 

echo " " >> valgrind_output.txt 2>&1

echo "LRU Tiled" >> valgrind_output.txt 2>&1

echo "== Running tiled test ..."
valgrind --tool=cachegrind --D1=32768,512,64 ./test-lru >> valgrind_output.txt 2>&1

