#!/bin/bash
mkdir build
cd build && cmake .. && make
cd ../tests
python3 make_tests.py ${1}
rm *.ll test-blocked-branch
clang -emit-llvm -S test-${1}.c -Xclang -disable-O0-optnone -o test-blocked-branch.ll
opt -load-pass-plugin=../build/tilingpass_branchless/tilingpass_branchless.so -passes="tilingpass_branchless,dot-cfg" test-blocked-branch.ll -o test-blocked-branch-output.ll
clang test-blocked-branch-output.ll -Xclang -disable-O0-optnone -o test-blocked-branch
clang -O0 test-${1}.c -o test-unblocked
cat .main.dot | dot -Tpdf > test-blocked-branch-${1}.pdf
echo "== Running non-tiled test ..."
valgrind --tool=cachegrind --D1=32768,512,64 ./test-unblocked >> unblocked.log 
./test-unblocked
echo "== Running tiled test ..."
valgrind --tool=cachegrind --D1=32768,512,64 ./test-blocked-branch >> blocked.log
./test-blocked-branch