#!/bin/bash
mkdir build
cd build && cmake .. && make
cd ../tests
python3 make_tests.py ${1}
rm *.ll test-sqrt valgrind*
clang -emit-llvm -S test-${1}.c -Xclang -disable-O0-optnone -o test-sqrt.ll
opt -load-pass-plugin=../build/tilingpass_sqrt/tilingpass_sqrt.so -passes="tilingpass_sqrt" test-sqrt.ll -o test-sqrt-output.ll
# opt -load-pass-plugin=../build/tilingpass/tilingpass.so -passes="tilingpass,dot-cfg" test-sqrt.ll -o test-sqrt-output.ll
clang test-sqrt-output.ll -Xclang -disable-O0-optnone -o test-sqrt
clang -O0 test-${1}.c -o test-unblocked
# cat .main.dot | dot -Tpdf > test-sqrt-${1}.pdf
echo "== Running non-tiled test ..."
echo "Non-tiled" >> valgrind_output.txt 2>&1
valgrind --tool=cachegrind --D1=32768,512,64 ./test-unblocked >> valgrind_output.txt 2>&1

echo "  " >> valgrind_output.txt 2>&1
echo "SQRT Tiled" >> valgrind_output.txt 2>&1
valgrind --tool=cachegrind --D1=32768,512,64 ./test-sqrt >> valgrind_output.txt 2>&1
