#!/bin/bash
mkdir build
cd build && cmake .. && make
cd ../tests
python3 make_tests.py ${1}
rm *.ll test-factor
clang -emit-llvm -S test-${1}.c -Xclang -disable-O0-optnone -o test-factor.ll
opt -load-pass-plugin=../build/tilingpass_factor/tilingpass_factor.so -passes="tilingpass_factor" test-factor.ll -o test-factor-output.ll
# opt -load-pass-plugin=../build/tilingpass_factor/tilingpass_factor.so -passes="tilingpass_factor,dot-cfg" test-factor.ll -o test-factor-output.ll
clang test-factor-output.ll -Xclang -disable-O0-optnone -o test-factor
clang -O0 test-${1}.c -o test-unblocked
# cat .main.dot | dot -Tpdf > test-blocked-factor-${1}.pdf
echo "== Running non-tiled test ..."
valgrind --tool=cachegrind --D1=32768,512,64 ./test-unblocked
echo "== Running tiled test ..."
valgrind --tool=cachegrind --D1=32768,512,64 ./test-factor
